import "../globals.css"


export const metadata = {
  title: 'Sanity Studio',
  description: 'Generated by Baggina',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        { children }
      </body>
    </html>
  )
}